include_recipe "../cookbooks/network/default.rb"
include_recipe "../cookbooks/vim/default.rb"
include_recipe "../cookbooks/tree/default.rb"
include_recipe "../cookbooks/lv/default.rb"
include_recipe "../cookbooks/docker-dockerui/default.rb"
include_recipe "../cookbooks/nodejs_v7/default.rb"
include_recipe "../cookbooks/itamae-plugin-resource-npm/default.rb"
